name: bmi_calculator
description: A simple BMI calculator app built using Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png  # Add your logo here (create an "assets" folder and add a logo image).
